CREATE TABLE IF NOT EXISTS "weather" (
    "id" SERIAL PRIMARY KEY,
    "provider" VARCHAR(50) NOT NULL,
    "city" VARCHAR(255) NOT NULL,
    "country" VARCHAR(255) NOT NULL,
    "latitude" FLOAT NOT NULL,
    "longitude" FLOAT NOT NULL,
    "temperature" FLOAT NOT NULL,
    "feelsLike" FLOAT NOT NULL,
    "tempMin" FLOAT NOT NULL,
    "tempMax" FLOAT NOT NULL,
    "humidity" INTEGER NOT NULL,
    "pressure" INTEGER NOT NULL,
    "windSpeed" FLOAT NOT NULL,
    "windDirection" INTEGER NOT NULL,
    "conditionMain" VARCHAR(255) NOT NULL,
    "conditionDescription" VARCHAR(255) NOT NULL,
    "conditionIcon" VARCHAR(255) NOT NULL,
    "timestamp" TIMESTAMP NOT NULL,
    "createdAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
